### ISSUE TITLE
MQTT - basic authentication via Username/Password

### ISSUE THREAD

**Issue by BlackyS** [geeks-r-us/mqtt-panel#1]
Thank you soo much for sharing!!! I was struggling finding a proper IoT dashboard, and Grafana was always on my mind, but a proper MQTT Implementation was missing - until I found your github-repo!
Hence: thank you for providing the "missing link" I was looking for :)

Maybe it is too early to ask, but do plan to add basic MQTT security to it? Like User/Password authentication?

Thank you soooo much! 
Have a nice weekend!
BR
Martin

**Comment by geeks-r-us** [comment]
Adding should no big deal. You can find a quick try here: https://github.com/geeks-r-us/mqtt-panel/tree/f/auth
Currently I have not set up a mqtt with auth (running them inside local docker networks) so I wasn't able to test it yet. 

Any feedback is welcome.

**Comment by BlackyS** [comment]
Wow - thank you so much for your fast response and the implementation!!!! 
(I actually struggled a bit with compiling the code - as I'm not into web programming - but finally I got it up and running ... yeahhh!)

=> **Publishing** a topic via WS+Basic Auth **works very well**!
=> **Subscribing** to a topic **requires a refresh** of the dashboard (e.g set the refresh rate to 5s) - this is a bit limiting (it would be great if this would be possible without the need to wait for the refresh)

But in general I have to admit: this is really awesome and it is definitely something I was looking for!!
Thanks a million and BR
Martin

**Comment by geeks-r-us** [comment]
Thx for testing. 
The refresh issue should be fixed now.

**Comment by BlackyS** [comment]
Wow - great!!! THX!!! 
I just complied/installed the plugin and run a couple tests - and it looks really good!!! Thank you for your support - I really like it!!!

Please keep this project alive - as it has quite some potential (in my eyes!) :)

**Comment by geeks-r-us** [comment]
Thx for testing.
Branche is merged into version 1.0.2
