### ISSUE TITLE
Come on guys!

### ISSUE THREAD

**Issue by na-am** [geeks-r-us/mqtt-panel#10]
https://github.com/geeks-r-us/mqtt-panel/releases/download/v1.0.**4**/geeksrus-mqtt-panel-1.0.**4**.zip;mqtt-panel
is not valid as described on the code page

it's
https://github.com/geeks-r-us/mqtt-panel/releases/download/v1.0.**5**/geeksrus-mqtt-panel-1.0.**5**.zip;mqtt-panel

that's no quality, that's embarrassesing

**Comment by geeks-r-us** [comment]
Thanks for that hint.

If you feel not confident with the quality of the plugin, please don't use it.
