### ISSUE TITLE
[FR] Use variables in input fields for topics

### ISSUE THREAD

**Issue by corgan2222** [geeks-r-us/mqtt-panel#13]
Hello

Thanks for this plugin. This is exactly what I was looking for.
I want to control my Unraid Dockers and VMs from inside Grafana.
It's running fine with the inoffz. Unraid API and your Plugin, if I only have it one time with hard coded topics.

But it would be awesome, if it would be dynamic and would use variables for the name and topic.
I have set up a query which gives me all Docker Names.
The Topics are always in the same style as

homeassistant/serva4/$dockers/status
homeassistant/serva4/$dockers/dockerState

But if I use the $docker variable it's not working. Could you add support for variable in the name and topic input fields?

![grafana](https://knaak.org/screens/firefox_2vy54ftkkn.png)

**Comment by geeks-r-us** [comment]
This should be an easy one. And will be added in the next version.
