### ISSUE TITLE
How to use the URL in this plugin: Is it possible?

### ISSUE THREAD

**Issue by felipedeodomingues** [geeks-r-us/mqtt-panel#15]
Hi, I'm a beginner and I use Grafana for process monitoring. Now, I installed this plugin painel-mqtt with the intention of controlling the speed of an motor. I already do this by sending values via browser via URL http: //192.xxx.1.201: 3005/api/daq/wuout?Channel=1&value=<VARIABLE I WANT TO SEND USING SLIDER CONTROL>.

Would it be possible to do this control without using MQTT? I am using NATS Broker.
Thanks!

**Comment by geeks-r-us** [comment]
Not with this plugin. It is for mqtt communication only
