### ISSUE TITLE
MQTT Button with preset Text

### ISSUE THREAD

**Issue by ManuelBu96** [geeks-r-us/mqtt-panel#17]
Hello,

is it possible to create only a button with a preset Text? Only the Button should shown in the Panel.

**Comment by ManuelBu96** [comment]
When you need help i would implement the Code. I am a German Developer.

**Comment by geeks-r-us** [comment]
PR's are always welcome. :+1: 
Currently I check how much effort it would take to bring the plugin from Angular to React because Grafana deprecated Angular. 
So maybe an implementation after that decision would save some work :) 

See #19
