### ISSUE TITLE
Send Grafana Variable with MQTT

### ISSUE THREAD

**Issue by ManuelBu96** [geeks-r-us/mqtt-panel#20]
A new idea is to send a Variable from Grafana with MQTT. When you use the Button option it have to be possible to insert a Variable from set from Grafana.
![grafik](https://user-images.githubusercontent.com/24299595/102991460-869f0700-4519-11eb-9261-ca9a696a90a3.png)

**Comment by geeks-r-us** [comment]
Nice idea.

Is it already working? 
So I would love to merge it.

**Comment by ManuelBu96** [comment]
Yes worked in my Fork.
The Variable have to be like $Variable.
You only have to change this line in the publish() function:
From
`value = this.panel.value.toString();`
To
`value = this.templateSrv.replace(this.panel.value.toString(), this.templateSrv.getVariables());`

I have change the Button that I have added. So the "Text" Textbox would not change after a publish. So the response have no influence and will not change the Text (replace the variable).

**Comment by geeks-r-us** [comment]
That was quick :) :+1: 

I preparing the new version which also fixes #12 and adds #13 right now.
Let's have a look if I can include it flawlessly

**Comment by ManuelBu96** [comment]
> 
> 
> That was quick :) 👍
> 
> I preparing the new version which also fixes #12 and adds #13 right now.
> Let's have a look if I can include it flawlessly

Yes it was already done. Only forget to add the Merge Request.
