### ISSUE TITLE
WS unencrypted does not connect

### ISSUE THREAD

**Issue by tatuiot** [geeks-r-us/mqtt-panel#3]
Hi Iam testing mqtt for grafana. It seems to be a great tool... 
I have installed it on my own VPS, mosquitto is also running on the same server, Ubuntu 18.04 , I can connect from http://www.hivemq.com/demos/websocket-client/  right away.
But I cannot connect from mqtt-panel locally. I also tried to connect from mqtt-panel out to test.mosquitto.org:8080 but no success, when I press the "test" button the red dot remains.
I have grafana running, with influxdb plug in... everything is working, but , I cannot make it work with mqtt-panel , how can I debug and see what is going on?
Thanks a lot in advance

**Comment by geeks-r-us** [comment]
The websocket server must be reachable from your browser. 
In most browsers you can hit F12 to see console with log output.

**Comment by geeks-r-us** [comment]
Hi,
the mosquitto websocket needs to be reachable within the network. (localhost won't work in this setup.
Most browsers show the console log when hitting F12.
