### ISSUE TITLE
Slider publishes by itself

### ISSUE THREAD

**Issue by Webbeh** [geeks-r-us/mqtt-panel#30]
Sometimes, after connecting on a panel, the slider will publish its default setting value right after connecting, without any user input.

This happens after, for example, reloading the same dashboard a few times.

Don't know how to reproduce it consistently yet, will let you know if I do.

**Comment by Webbeh** [comment]
Hi again,

After testing a few times, it seems to be due to a slow connection.

The slider doesn't receive the value right away, and publishes the "default" (middle) value.

Any way to prevent this from happening ?

**Comment by hildogjr** [comment]
Appear that https://github.com/Webbeh/mqtt-panel/commit/374dfd8103f9a0c54d0776b59551e5d281f4c37a is related with this fix.

@Webbeh, could you pull request the fix?

**Comment by Webbeh** [comment]
It's a big mess because I'm an idiot and pushed everything. 

But there it is. 

https://github.com/geeks-r-us/mqtt-panel/pull/37
