### ISSUE TITLE
Plugin works with Grafana 7.0.3?

### ISSUE THREAD

**Issue by sbstn-0x2a** [geeks-r-us/mqtt-panel#6]
Hi.
At first, a great thank you for your work on a mqtt plugin for grafana!

~~I cant see the plugin in panel tab.
Is your plugin working with grafana 7.0.3?
On plugin Site i see dependencies 6.3.x~~

It works after 10 Minutes of waiting time.

Thank you in advance.
Toxo

**Comment by geeks-r-us** [comment]
Good to know.
Thx for using
