### ISSUE TITLE
How to compile this for Grafana 7.0.3 on Ubuntu 

### ISSUE THREAD

**Issue by dewell1** [geeks-r-us/mqtt-panel#7]
I approached this naively and expected the panel to work right away ;) Grafana recognized the panel but threw an error, assuming I haven't compiled the panel.
My approach with yarn install and yarn build inside the mqtt-panel-folder didn't work yet so I wondered if I'm even on the right track here.

Best regards and thanks for the great work!

**Comment by geeks-r-us** [comment]
Can you describe where you have placed the files? 

Easiest way is to install it using cli : https://grafana.com/docs/grafana/latest/plugins/installation/#install-plugin-on-local-grafana

**Comment by dewell1** [comment]
Hello, thanks for the quick answer.
I use Ubuntu 18.04.4 LTS and copied the extracted files to grafana/data/plugins, the folder is now called mqtt-panel-master. My first try was using grafana-cli but with "plugins ls" i couldn't find the MQTT-Panel, so I assumed I have to install it myself.

Inside the default.ini under the conf folder I set the path for the plugins:
`# Directory where grafana will automatically scan and look for plugins
plugins = data/plugins`

This is the result of "yarn install":
```
$ yarn install
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "@babel/preset-env@7.9.0" is incompatible with requested version "@babel/preset-env@7.8.3"
success Already up-to-date.
Done in 1.09s.
```
And this of "yarn build":
```
yarn run v1.22.4
$ grafana-toolkit plugin:build
✔ Preparing
✔ Linting
 PASS  src/module.test.ts

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.28s
Ran all test suites with tests matching "".
✔ Running tests
⠦ Compiling...

#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0x7ffe49214220Illegal instruction (core dumped)
error Command failed with exit code 132.
```

Grafana still finds the plugin but the functionality doesn't work, doesn't connect to anything yet and I suspect that it's because of this error, not a network issue

**Comment by dewell1** [comment]
> 
> 
> Can you describe where you have placed the files?
> 
> Easiest way is to install it using cli : https://grafana.com/docs/grafana/latest/plugins/installation/#install-plugin-on-local-grafana

Hello! Could you tell me how I can find this plugin with CLI? ./grafana-cli plugins list-remote doesn't show this plugin

**Comment by geeks-r-us** [comment]
Sorry for late answer: easiest way is just to install it from web:
https://grafana.com/docs/grafana/latest/administration/cli/#override-default-plugin-zip-url

    grafana-cli --pluginUrl https://github.com/geeks-r-us/mqtt-panel/releases/download/v1.0.3/geeksrus-mqtt-panel-1.0.3.zip plugins install mqtt-panel.zip

Otherwise you need to copy the dist directory including all sub directories into the grafana plugin folder.
It would be good to rename dist into geeksrus-mqtt-panel  to prevent collisions with other plugins

**Comment by dewell1** [comment]
Thanks a lot, it works well now!
One more question about a possible network issue. Grafana runs locally on a server, like 1.1.1.1., an mqtt broker is running on another server with port 1883 in the same subnet under 1.1.1.2 and I configure the MQTT plugin with this data.
I can reach Grafana from a anywhere with 1.1.1.1:3000 but I can't get a connection between the plugin and the broker yet.
I expected that, since I can reach the server with grafana with my browser, I can also reach that same subnet with the plugin ...

**Comment by geeks-r-us** [comment]
as described not the grafana server needs to be able to connect to the mqtt server but your browser must be able.
