### ISSUE TITLE
how  to send downlink to device #thethingsnetwork

### ISSUE THREAD

**Issue by SubashYuvi** [geeks-r-us/mqtt-panel#8]
is possible to **send data to iot device using grafana** . as like control a  relay on and off. 

please help the **server configuration** in mqtt-panel

**Comment by geeks-r-us** [comment]
This depends on your project.
All you need to setup mqtt communication with ttn is documented here: https://www.thethingsnetwork.org/docs/applications/mqtt/quick-start.html

But be carful ttn allows just 20 downlinks a day... so it's not suited very well for control tasks.

**Comment by SubashYuvi** [comment]
okay.. Thanksss

**Comment by SubashYuvi** [comment]
can you please send any documentation for send downlink data using via mqtt-panel  #Grafana to Device

**Comment by SubashYuvi** [comment]
![Screenshot](https://user-images.githubusercontent.com/57889888/89097160-1a9cf480-d3fa-11ea-8cd7-663722b7e320.png)

can you please tell me the configuration example of TTN device

**Comment by geeks-r-us** [comment]
as described in the link you also need to authenticate with your credentials
